language: rust

env:
  global:
    - secure: C6dtZjIXukGFq+dV0/w6INZX1dps6kDfONDzubEqT+0UjsrGgXSugBNspuDE4kTv8yJ9qFNv/69LfvjuYpERRaJZuv66nS2MDpBWugXwZ/4mdsaBfho/Zhuajl4ff4Dn0hvYs9olrZpJK6L/byTLd1w4ugw77ngTyc+rwR+rB4U=
    - secure: CF2BlYNHixofAFZVM1BplYfCYWMQA4bidBs5NYKI1pF37Sv9v7a+Viw4EWJT0/lsvePQ3vmEHcyLMSvQJweK3cQatIrvPrHX7QMk10f9X0rC9BeGt5kIS7IexThKNsM3CxYJYy4znO6GkqbTVIWVhEVOBIevgyM5/GZTH5o4pYc=

script:
    - cargo test --verbose && cargo doc --verbose --no-deps

after_script:
  - ./up_doc.sh
