[package]
name = "lmdb-rs"
version = "0.2.0"
authors = ["Valerii Hiora <valerii.hiora@gmail.com>"]
license = "MIT"
description = "LMDB bindings"
repository = "https://github.com/vhbit/lmdb-rs"
documentation = "https://vhbit.github.io/lmdb-rs/lmdb-rs"
readme = "README.md"
keywords = ["lmdb", "db", "key-value", "kvs", "kv"]

[dependencies.liblmdb-sys]
path = "liblmdb-sys"
version = "0.0.6"

[dependencies]
log = "0.2"
regex = "0.1.10"
bitflags = "0.1.1"
